Repository LCSB-BioCore/SBML.jl, pull requests merged in 2021-07, with the labels that each got.

#113 add issue templates to promote decent format of bug reports
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/enhancement.md
Labels: :star::sparkles: Quality :sparkles::star:

#114 fix argument order and count for piecewise function
  Project.toml
  src/SBML.jl
  src/symbolics.jl
  test/symbolics.jl
Labels: bug :bug:

#109 Use `Unitful` for units, instead of a custom struct
  Project.toml
  src/SBML.jl
  src/readsbml.jl
  src/structs.jl
  src/utils.jl
  test/data/units.xml
  test/ecoli_flux.jl
  test/loadmodels.jl
  test/runtests.jl
Labels: :x: breaking :x:, enhancement

#122 Rename some functions to something easier understand
  src/SBML.jl
  src/utils.jl
  test/ecoli_flux.jl
  test/loadmodels.jl
Labels: :star::sparkles: Quality :sparkles::star:, :x: breaking :x:
