Repository LCSB-BioCore/SBML.jl, pull requests merged in 2022-05, with the labels that each got.

#196 Read also name of unit definitions
  src/readsbml.jl
  src/structs.jl
  src/unitful.jl
  src/utils.jl
Labels: :x: breaking :x:

#198 externalize the support for converting to Symbolics
  Project.toml
  src/SBML.jl
  src/interpret.jl
  src/symbolics.jl
  test/interpret.jl
  test/loadmodels.jl
  test/runtests.jl
  test/symbolics.jl
Labels: :x: breaking :x:

#199 extensive math correctly exposes compartment identifications
  src/interpret.jl
  src/utils.jl
  test/loadmodels.jl
  test/symbolics.jl
Labels: :star::sparkles: Quality :sparkles::star:, :x: breaking :x:

#200 DocStringExtensions + some extra fixes
  .github/workflows/docs.yml
  Project.toml
  docs/make.jl
  docs/src/functions.md
  src/SBML.jl
  src/converters.jl
  src/interpret.jl
  src/math.jl
  src/readsbml.jl
  src/structs.jl
  src/unitful.jl
  src/utils.jl
  src/version.jl
Labels: documentation, :star::sparkles: Quality :sparkles::star:
